/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PrivateVoting__factory } from "./PrivateVoting__factory";
export { PrivateVotingSimple__factory } from "./PrivateVotingSimple__factory";
