/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrivateVoting } from "./PrivateVoting";
export type { PrivateVotingSimple } from "./PrivateVotingSimple";
