/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateVotingSimpleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeDecryptor"
      | "authorizedDecryptors"
      | "closePoll"
      | "createPoll"
      | "getPollInfo"
      | "getPollOptions"
      | "getVoteCount"
      | "hasVoted"
      | "isAuthorizedDecryptor"
      | "isDecrypted"
      | "pollCount"
      | "polls"
      | "requestDecryption"
      | "revokeDecryptor"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecryptionRequested"
      | "DecryptorAuthorized"
      | "DecryptorRevoked"
      | "PollClosed"
      | "PollCreated"
      | "VoteCasted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeDecryptor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedDecryptors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closePoll",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPoll",
    values: [string, string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPollInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPollOptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteCount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedDecryptor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDecrypted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pollCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "polls", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "requestDecryption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDecryptor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeDecryptor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedDecryptors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closePoll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createPoll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPollInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPollOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedDecryptor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDecrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pollCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "polls", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDecryptor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace DecryptionRequestedEvent {
  export type InputTuple = [pollId: BigNumberish, requester: AddressLike];
  export type OutputTuple = [pollId: bigint, requester: string];
  export interface OutputObject {
    pollId: bigint;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptorAuthorizedEvent {
  export type InputTuple = [decryptor: AddressLike];
  export type OutputTuple = [decryptor: string];
  export interface OutputObject {
    decryptor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptorRevokedEvent {
  export type InputTuple = [decryptor: AddressLike];
  export type OutputTuple = [decryptor: string];
  export interface OutputObject {
    decryptor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PollClosedEvent {
  export type InputTuple = [pollId: BigNumberish];
  export type OutputTuple = [pollId: bigint];
  export interface OutputObject {
    pollId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PollCreatedEvent {
  export type InputTuple = [
    pollId: BigNumberish,
    title: string,
    creator: AddressLike,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    pollId: bigint,
    title: string,
    creator: string,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    pollId: bigint;
    title: string;
    creator: string;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastedEvent {
  export type InputTuple = [pollId: BigNumberish, voter: AddressLike];
  export type OutputTuple = [pollId: bigint, voter: string];
  export interface OutputObject {
    pollId: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateVotingSimple extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateVotingSimple;
  waitForDeployment(): Promise<this>;

  interface: PrivateVotingSimpleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeDecryptor: TypedContractMethod<
    [decryptor: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedDecryptors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  closePoll: TypedContractMethod<[pollId: BigNumberish], [void], "nonpayable">;

  createPoll: TypedContractMethod<
    [
      title: string,
      description: string,
      options: string[],
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getPollInfo: TypedContractMethod<
    [pollId: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, string, bigint] & {
        title: string;
        description: string;
        startTime: bigint;
        endTime: bigint;
        isActive: boolean;
        creator: string;
        totalVoters: bigint;
      }
    ],
    "view"
  >;

  getPollOptions: TypedContractMethod<
    [pollId: BigNumberish],
    [string[]],
    "view"
  >;

  getVoteCount: TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BigNumberish],
    [bigint],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [pollId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;

  isAuthorizedDecryptor: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  isDecrypted: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  pollCount: TypedContractMethod<[], [bigint], "view">;

  polls: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, string, bigint] & {
        title: string;
        description: string;
        startTime: bigint;
        endTime: bigint;
        isActive: boolean;
        creator: string;
        totalVoters: bigint;
      }
    ],
    "view"
  >;

  requestDecryption: TypedContractMethod<
    [pollId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  revokeDecryptor: TypedContractMethod<
    [decryptor: AddressLike],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeDecryptor"
  ): TypedContractMethod<[decryptor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedDecryptors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "closePoll"
  ): TypedContractMethod<[pollId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPoll"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      options: string[],
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPollInfo"
  ): TypedContractMethod<
    [pollId: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, string, bigint] & {
        title: string;
        description: string;
        startTime: bigint;
        endTime: bigint;
        isActive: boolean;
        creator: string;
        totalVoters: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPollOptions"
  ): TypedContractMethod<[pollId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVoteCount"
  ): TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [pollId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuthorizedDecryptor"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDecrypted"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "pollCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "polls"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, string, bigint] & {
        title: string;
        description: string;
        startTime: bigint;
        endTime: bigint;
        isActive: boolean;
        creator: string;
        totalVoters: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestDecryption"
  ): TypedContractMethod<[pollId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeDecryptor"
  ): TypedContractMethod<[decryptor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DecryptionRequested"
  ): TypedContractEvent<
    DecryptionRequestedEvent.InputTuple,
    DecryptionRequestedEvent.OutputTuple,
    DecryptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptorAuthorized"
  ): TypedContractEvent<
    DecryptorAuthorizedEvent.InputTuple,
    DecryptorAuthorizedEvent.OutputTuple,
    DecryptorAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptorRevoked"
  ): TypedContractEvent<
    DecryptorRevokedEvent.InputTuple,
    DecryptorRevokedEvent.OutputTuple,
    DecryptorRevokedEvent.OutputObject
  >;
  getEvent(
    key: "PollClosed"
  ): TypedContractEvent<
    PollClosedEvent.InputTuple,
    PollClosedEvent.OutputTuple,
    PollClosedEvent.OutputObject
  >;
  getEvent(
    key: "PollCreated"
  ): TypedContractEvent<
    PollCreatedEvent.InputTuple,
    PollCreatedEvent.OutputTuple,
    PollCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCasted"
  ): TypedContractEvent<
    VoteCastedEvent.InputTuple,
    VoteCastedEvent.OutputTuple,
    VoteCastedEvent.OutputObject
  >;

  filters: {
    "DecryptionRequested(uint256,address)": TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;
    DecryptionRequested: TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;

    "DecryptorAuthorized(address)": TypedContractEvent<
      DecryptorAuthorizedEvent.InputTuple,
      DecryptorAuthorizedEvent.OutputTuple,
      DecryptorAuthorizedEvent.OutputObject
    >;
    DecryptorAuthorized: TypedContractEvent<
      DecryptorAuthorizedEvent.InputTuple,
      DecryptorAuthorizedEvent.OutputTuple,
      DecryptorAuthorizedEvent.OutputObject
    >;

    "DecryptorRevoked(address)": TypedContractEvent<
      DecryptorRevokedEvent.InputTuple,
      DecryptorRevokedEvent.OutputTuple,
      DecryptorRevokedEvent.OutputObject
    >;
    DecryptorRevoked: TypedContractEvent<
      DecryptorRevokedEvent.InputTuple,
      DecryptorRevokedEvent.OutputTuple,
      DecryptorRevokedEvent.OutputObject
    >;

    "PollClosed(uint256)": TypedContractEvent<
      PollClosedEvent.InputTuple,
      PollClosedEvent.OutputTuple,
      PollClosedEvent.OutputObject
    >;
    PollClosed: TypedContractEvent<
      PollClosedEvent.InputTuple,
      PollClosedEvent.OutputTuple,
      PollClosedEvent.OutputObject
    >;

    "PollCreated(uint256,string,address,uint256,uint256)": TypedContractEvent<
      PollCreatedEvent.InputTuple,
      PollCreatedEvent.OutputTuple,
      PollCreatedEvent.OutputObject
    >;
    PollCreated: TypedContractEvent<
      PollCreatedEvent.InputTuple,
      PollCreatedEvent.OutputTuple,
      PollCreatedEvent.OutputObject
    >;

    "VoteCasted(uint256,address)": TypedContractEvent<
      VoteCastedEvent.InputTuple,
      VoteCastedEvent.OutputTuple,
      VoteCastedEvent.OutputObject
    >;
    VoteCasted: TypedContractEvent<
      VoteCastedEvent.InputTuple,
      VoteCastedEvent.OutputTuple,
      VoteCastedEvent.OutputObject
    >;
  };
}
